# Don't edit this file!
# It is automatically updated after every release of https://github.com/47degrees/.github
# If you want to suggest a change, please open a PR or issue in that repository

pull_request_rules:
  - name: automatically merge & label scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=test
    actions:
      merge:
        method: squash
      label:
        add: [scala-steward]
  - name: automatically merge & label 47erbot's PRs
    conditions:
      - author=47erbot
      - status-success=test
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
