resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("org.scala-exercises" % "sbt-exercise"      % "0.6.0-SNAPSHOT")
addSbtPlugin("com.geirsson"        % "sbt-ci-release"    % "1.5.3")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"          % "2.1.5")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"      % "2.3.4")
addSbtPlugin("de.heikoseeberger"   % "sbt-header"        % "5.6.0")
addSbtPlugin("com.alejandrohdezma" %% "sbt-github"       % "0.8.0")
addSbtPlugin("com.alejandrohdezma" % "sbt-github-header" % "0.8.0")
addSbtPlugin("com.alejandrohdezma" % "sbt-github-mdoc"   % "0.8.0")
addSbtPlugin("com.alejandrohdezma" % "sbt-mdoc-toc"      % "0.2")
